name: Daily Pokémon Drop

on:
  schedule:
    - cron: '45 7 * * *'  
  workflow_dispatch:

jobs:
  run-potd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: python -m pip install requests pillow


      - name: Run POTD.py
        run: python POTD.py

      - name: Debug Python environment
        run: |
         python -m pip show requests
         python -c "import requests; print('Using requests from:', requests.__file__)"
